/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./docs/**/*.{html,js,vue}", ".vitepress/**/*.{html,js,vue}"],
  theme: {
    extend: {
      colors: {
        "vp-c-bg": "var(--vp-c-bg)",
        "vp-c-bg-alt": "var(--vp-c-bg-alt)",
        "vp-c-bg-elv": "var(--vp-c-bg-elv)",
        "vp-c-bg-soft": "var(--vp-c-bg-soft)",
        "vp-c-border": "var(--vp-c-border)",
        "vp-c-divider": "var(--vp-c-divider)",
        "vp-c-gutter": "var(--vp-c-gutter)",
        "vp-c-text-1": "var(--vp-c-text-1)",
        "vp-c-text-2": "var(--vp-c-text-2)",
        "vp-c-text-3": "var(--vp-c-text-3)",
        "vp-c-default-1": "var(--vp-c-default-1)",
        "vp-c-default-2": "var(--vp-c-default-2)",
        "vp-c-default-3": "var(--vp-c-default-3)",
        "vp-c-default-soft": "var(--vp-c-default-soft)",
        "vp-c-brand-1": "var(--vp-c-brand-1)",
        "vp-c-brand-2": "var(--vp-c-brand-2)",
        "vp-c-brand-3": "var(--vp-c-brand-3)",
        "vp-c-brand-soft": "var(--vp-c-brand-soft)",
        "vp-c-brand": "var(--vp-c-brand-1)",
        "vp-c-tip-1": "var(--vp-c-tip-1)",
        "vp-c-tip-2": "var(--vp-c-tip-2)",
        "vp-c-tip-3": "var(--vp-c-tip-3)",
        "vp-c-tip-soft": "var(--vp-c-tip-soft)",
        "vp-c-note-1": "var(--vp-c-note-1)",
        "vp-c-note-2": "var(--vp-c-note-2)",
        "vp-c-note-3": "var(--vp-c-note-3)",
        "vp-c-note-soft": "var(--vp-c-note-soft)",
        "vp-c-success-1": "var(--vp-c-success-1)",
        "vp-c-success-2": "var(--vp-c-success-2)",
        "vp-c-success-3": "var(--vp-c-success-3)",
        "vp-c-success-soft": "var(--vp-c-success-soft)",
        "vp-c-important-1": "var(--vp-c-important-1)",
        "vp-c-important-2": "var(--vp-c-important-2)",
        "vp-c-important-3": "var(--vp-c-important-3)",
        "vp-c-important-soft": "var(--vp-c-important-soft)",
        "vp-c-warning-1": "var(--vp-c-warning-1)",
        "vp-c-warning-2": "var(--vp-c-warning-2)",
        "vp-c-warning-3": "var(--vp-c-warning-3)",
        "vp-c-warning-soft": "var(--vp-c-warning-soft)",
        "vp-c-danger-1": "var(--vp-c-danger-1)",
        "vp-c-danger-2": "var(--vp-c-danger-2)",
        "vp-c-danger-3": "var(--vp-c-danger-3)",
        "vp-c-danger-soft": "var(--vp-c-danger-soft)",
        "vp-c-caution-1": "var(--vp-c-caution-1)",
        "vp-c-caution-2": "var(--vp-c-caution-2)",
        "vp-c-caution-3": "var(--vp-c-caution-3)",
        "vp-c-caution-soft": "var(--vp-c-caution-soft)",
      },
      fontFamily: {
        base: ["var(--vp-font-family-base)"],
        mono: ["var(--vp-font-family-mono)"],
      },
      boxShadow: {
        "vp-1": "var(--vp-shadow-1)",
        "vp-2": "var(--vp-shadow-2)",
        "vp-3": "var(--vp-shadow-3)",
        "vp-4": "var(--vp-shadow-4)",
        "vp-5": "var(--vp-shadow-5)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
